# Generated by Django 4.2.4 on 2024-03-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lineas_ahorro_app', '0002_alter_lineas_ahorro_cta_por_pas'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMP_CON_LIN_AHO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_imp', models.CharField(max_length=2, null=True)),
                ('descripcion', models.CharField(max_length=40, null=True)),
                ('ctaafeact', models.CharField(max_length=10, null=True)),
                ('ctaafeina', models.CharField(max_length=10, null=True)),
                ('ctaafeint', models.CharField(max_length=10, null=True)),
                ('ctaretfue', models.CharField(max_length=10, null=True)),
                ('linea_ahorro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lineas_ahorro_app.lineas_ahorro')),
            ],
            options={
                'db_table': 'imp_con_lin_aho',
                'unique_together': {('linea_ahorro', 'cod_imp')},
            },
        ),
    ]
