# Generated by Django 4.2.4 on 2024-04-19 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineas_ahorro_app', '0002_alter_lineas_ahorro_cta_por_pas'),
        ('contabilizacion_lineas_ahorros_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imp_con_lin_aho',
            name='cod_imp',
            field=models.CharField(max_length=2, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='imp_con_lin_aho',
            name='ctaafeact',
            field=models.CharField(max_length=10, null=True, verbose_name='Cuenta Activa'),
        ),
        migrations.AlterField(
            model_name='imp_con_lin_aho',
            name='ctaafeina',
            field=models.CharField(max_length=10, null=True, verbose_name='Cuenta Inactiva'),
        ),
        migrations.AlterField(
            model_name='imp_con_lin_aho',
            name='ctaafeint',
            field=models.CharField(max_length=10, null=True, verbose_name='Cuenta Intereses'),
        ),
        migrations.AlterField(
            model_name='imp_con_lin_aho',
            name='ctaretfue',
            field=models.CharField(max_length=10, null=True, verbose_name='Cuenta Retefuente'),
        ),
        migrations.AlterField(
            model_name='imp_con_lin_aho',
            name='descripcion',
            field=models.CharField(max_length=40, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='imp_con_lin_aho',
            name='linea_ahorro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lineas_ahorro_app.lineas_ahorro', verbose_name='Línea de Ahorro'),
        ),
    ]
