# Generated by Django 4.2.4 on 2024-03-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ctas_ahorros_app', '0003_alter_ctas_ahorro_asociado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTA_CDAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ampliacion', models.IntegerField(verbose_name='Ampliación')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('plazo_mes', models.IntegerField(blank=True, null=True, verbose_name='Plazo en Meses')),
                ('tiae', models.FloatField(blank=True, null=True, verbose_name='Tasa Interes Anual Efectiva')),
                ('Periodicidad', models.IntegerField(blank=True, null=True, verbose_name='Periodicidad')),
                ('cta_int_ret', models.CharField(max_length=10, null=True, verbose_name='Cuenta Contable Intereses')),
                ('aplicado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Aplicado?')),
                ('cta_aho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctas_ahorros_app.ctas_ahorro', verbose_name='Cuenta de Ahorro')),
            ],
            options={
                'db_table': 'cta_cdat',
                'unique_together': {('cta_aho', 'ampliacion')},
            },
        ),
    ]
