# Generated by Django 4.2.4 on 2024-06-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctas_ahorros_app', '0001_initial'),
        ('cdat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cta_cdat',
            name='cta_aho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ctas_ahorros_app.ctas_ahorro', verbose_name='Cuenta de Ahorro'),
        ),
    ]
