# Generated by Django 4.2.4 on 2024-03-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAMBIOS_CRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_cam', models.CharField(choices=[('2', 'Ajuste'), ('3', 'Descuento Pronto Pago'), ('4', 'Castigo/Condonación')], max_length=1, null=True)),
                ('capital', models.FloatField(blank=True, null=True)),
                ('int_cor', models.FloatField(blank=True, null=True)),
                ('int_mor', models.FloatField(blank=True, null=True)),
                ('pol_seg', models.FloatField(blank=True, null=True)),
                ('des_pp', models.FloatField(blank=True, null=True)),
                ('acreedor', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cambios_cre',
            },
        ),
    ]
