# Generated by Django 4.2.4 on 2024-03-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detalle_producto_app', '0001_initial'),
        ('cambios_creditos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambios_cre',
            name='det_pro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='detalle_producto_app.detalle_prod'),
        ),
        migrations.AlterUniqueTogether(
            name='cambios_cre',
            unique_together={('det_pro', 'tip_cam')},
        ),
    ]
