# Generated by Django 4.2.4 on 2024-06-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_producto_app', '0001_initial'),
        ('cambios_creditos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambios_cre',
            name='det_pro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='detalle_producto_app.detalle_prod', verbose_name='Detalle Producto'),
        ),
    ]
