# Generated by Django 4.2.4 on 2024-03-30 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_producto_app', '0002_initial'),
        ('cambios_creditos_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambios_cre',
            name='acreedor',
            field=models.FloatField(blank=True, null=True, verbose_name='Acreedor'),
        ),
        migrations.AlterField(
            model_name='cambios_cre',
            name='capital',
            field=models.FloatField(blank=True, null=True, verbose_name='Capital'),
        ),
        migrations.AlterField(
            model_name='cambios_cre',
            name='des_pp',
            field=models.FloatField(blank=True, null=True, verbose_name='Descuento Pronto Pago'),
        ),
        migrations.AlterField(
            model_name='cambios_cre',
            name='det_pro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='detalle_producto_app.detalle_prod', verbose_name='Detalle Producto'),
        ),
        migrations.AlterField(
            model_name='cambios_cre',
            name='int_cor',
            field=models.FloatField(blank=True, null=True, verbose_name='Interés Corriente'),
        ),
        migrations.AlterField(
            model_name='cambios_cre',
            name='int_mor',
            field=models.FloatField(blank=True, null=True, verbose_name='Interés de Mora'),
        ),
        migrations.AlterField(
            model_name='cambios_cre',
            name='pol_seg',
            field=models.FloatField(blank=True, null=True, verbose_name='Póliza'),
        ),
        migrations.AlterField(
            model_name='cambios_cre',
            name='tip_cam',
            field=models.CharField(choices=[('2', 'Ajuste'), ('3', 'Descuento Pronto Pago'), ('4', 'Castigo/Condonación')], max_length=1, null=True, verbose_name='Tipo de Cambio?'),
        ),
    ]
