# Generated by Django 4.2.4 on 2024-03-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_app', '0006_alter_clientes_fin_lic_alter_clientes_ini_lic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAT_DES_DIA_CRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('categoria', models.CharField(choices=[('A', 'Normal'), ('B', 'Apreciable'), ('C', 'En Peligro'), ('D', 'En Mora'), ('E', 'Irrecuperable'), ('F', 'Castigado')], max_length=1)),
                ('minimo_dias', models.IntegerField(null=True)),
                ('maximo_dias', models.IntegerField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_app.clientes')),
            ],
            options={
                'db_table': 'cat_des_dia_cre',
                'unique_together': {('cliente', 'codigo', 'categoria')},
            },
        ),
    ]
