# Generated by Django 4.2.4 on 2024-03-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficinas_app', '0002_oficinas_ciudad_oficinas_direccion_alter_oficinas_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='cierre_mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('protegido', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('tot_deb', models.FloatField(blank=True, null=True)),
                ('tot_cre', models.FloatField(blank=True, null=True)),
                ('fec_cie', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.CharField(max_length=16)),
                ('oficina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oficinas_app.oficinas')),
            ],
            options={
                'db_table': 'cierre_mes',
                'unique_together': {('oficina', 'fecha')},
            },
        ),
    ]
