# Generated by Django 4.2.4 on 2024-03-30 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas_app', '0002_oficinas_ciudad_oficinas_direccion_alter_oficinas_id'),
        ('cierre_mensual_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierre_mes',
            name='fec_cie',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre'),
        ),
        migrations.AlterField(
            model_name='cierre_mes',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cierre_mes',
            name='oficina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oficinas_app.oficinas', verbose_name='Oficina'),
        ),
        migrations.AlterField(
            model_name='cierre_mes',
            name='protegido',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Protegido?'),
        ),
        migrations.AlterField(
            model_name='cierre_mes',
            name='tot_cre',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Crédito'),
        ),
        migrations.AlterField(
            model_name='cierre_mes',
            name='tot_deb',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Débito'),
        ),
        migrations.AlterField(
            model_name='cierre_mes',
            name='usuario',
            field=models.CharField(max_length=16, verbose_name='Usuario'),
        ),
    ]
