# Generated by Django 4.2.4 on 2024-05-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hecho_economico_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hecho_econo',
            name='anulado',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Anulado?'),
        ),
        migrations.AlterField(
            model_name='hecho_econo',
            name='canal',
            field=models.CharField(choices=[('ATM', 'Red de Cajeros'), ('POS', 'Compras en Comercios'), ('IVR', 'Audio Respuesta'), ('TRA', 'Transferencia'), ('CON', 'Consignación'), ('EFE', 'Efectivo'), ('CHE', 'Cheque'), ('GIR', 'Giro'), ('WEB', 'Portal Transaccional'), ('MOV', 'Banca Móvil'), ('OFI', 'Oficina'), ('CNB', 'Corresponsales Bancarios'), ('RAL', 'Redes Aliadas')], default='EFE', max_length=3, verbose_name='Canal'),
        ),
        migrations.AlterField(
            model_name='hecho_econo',
            name='protegido',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1, verbose_name='Protegido?'),
        ),
    ]
