# Generated by Django 4.2.4 on 2024-06-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos_app', '0003_alter_docto_conta_oficina'),
        ('hecho_economico_app', '0002_alter_hecho_econo_anulado_alter_hecho_econo_canal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hecho_econo',
            name='docto_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documentos_app.docto_conta', verbose_name='Documento'),
        ),
    ]
