# Generated by Django 4.2.4 on 2024-04-02 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0007_clientes_clase_coop_alter_clientes_id'),
        ('contabilizacion_capital_creditos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imp_con_cre',
            name='icta_des_int_pp',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre',
            name='kcta_gas_pro_gen',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre',
            name='kcta_gas_pro_ind',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre',
            name='kcta_pro_gen',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre',
            name='kcta_pro_gen_adi',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre',
            name='kcta_pte_cap',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre',
            name='kcta_pte_int',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre',
            name='kcta_rec_pro_gen',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre',
            name='kcta_rec_pro_ind',
        ),
        migrations.RemoveField(
            model_name='imp_con_cre',
            name='orden_i',
        ),
        migrations.AddField(
            model_name='imp_con_cre',
            name='kdet_gen',
            field=models.CharField(max_length=10, null=True, verbose_name='Provisión General'),
        ),
        migrations.AddField(
            model_name='imp_con_cre',
            name='kdet_gen_adi',
            field=models.CharField(max_length=10, null=True, verbose_name='Provisión General Adicional'),
        ),
        migrations.AddField(
            model_name='imp_con_cre',
            name='kdet_gen_gas',
            field=models.CharField(max_length=10, null=True, verbose_name='Cuenta Gasto Povisión'),
        ),
        migrations.AddField(
            model_name='imp_con_cre',
            name='kdet_gen_rec',
            field=models.CharField(max_length=10, null=True, verbose_name='Cuenta Provisión Recuperada'),
        ),
        migrations.AddField(
            model_name='imp_con_cre',
            name='kdet_ind_gas',
            field=models.CharField(max_length=10, null=True, verbose_name='Cuenta Provisión Individual Gasto'),
        ),
        migrations.AddField(
            model_name='imp_con_cre',
            name='kdet_ind_rec',
            field=models.CharField(max_length=10, null=True, verbose_name='Cuenta Provisión Individual Recuperada'),
        ),
        migrations.AddField(
            model_name='imp_con_cre',
            name='kdpp_ic',
            field=models.CharField(max_length=10, null=True, verbose_name='Cuenta Descuento Pronto Pago IC'),
        ),
        migrations.AddField(
            model_name='imp_con_cre',
            name='kic_orden_i',
            field=models.CharField(max_length=10, null=True, verbose_name='Cuenta de Orden IC'),
        ),
        migrations.AddField(
            model_name='imp_con_cre',
            name='kpte_cap',
            field=models.CharField(max_length=10, null=True, verbose_name='Cuenta Puente Capital'),
        ),
        migrations.AddField(
            model_name='imp_con_cre',
            name='kpte_ic',
            field=models.CharField(max_length=10, null=True, verbose_name='Cuenta Puente IC'),
        ),
        migrations.AlterField(
            model_name='imp_con_cre',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_app.clientes', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='imp_con_cre',
            name='cod_imp',
            field=models.CharField(max_length=2, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='imp_con_cre',
            name='cta_val',
            field=models.CharField(max_length=10, null=True, verbose_name='Cuenta Valorización'),
        ),
        migrations.AlterField(
            model_name='imp_con_cre',
            name='descripcion',
            field=models.CharField(max_length=40, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='imp_con_cre',
            name='kcta_ingreso',
            field=models.CharField(max_length=10, null=True, verbose_name='Cuenta Ingreso'),
        ),
    ]
