"""
Django settings for Justo_proy project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kd!no$3gdo54*7wl6q%*5uym&#kwix!vc8(%vsrjo*$_l+os)m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'crispy_forms',
    'crispy_bootstrap5',
    'colorfield',
    'admin_interface',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ampliacion_cdat_app',
    'aportes_app',
    'asociados_app',
    'backup_bd',
    'cambios_creditos_app',
    'categorias_creditos_app',
    'causacion_creditos_app',
    'cdat_app',
    'centrocostos_app',
    'cierre_mensual_app',
    'clientes_app',
    'conceptos_app',
    'contabilizacion_capital_creditos_app',
    'contabilizacion_intereses_creditos_app',
    'contabilizacion_lineas_ahorros_app',
    'creditos_app',
    'ctas_ahorros_app',
    'cuentas_app',
    'destino_credito_app',
    'detalle_economico_app',
    'detalle_producto_app',
    'documentos_app',
    'estados_financieros_app',
    'hecho_economico_app',
    'historico_ctas_ahorros_app',
    'justo_app',
    'lineas_ahorro_app',
    'lineas_credito_app',
    'liquidacion_cdat_app',    
    'localidades_app',
    'movimiento_caja_app',
    'oficinas_app',
    'originacion_app',
    'pagadores_app',
    'retefuente_ahorros_app',
    'tasas_lin_aho_app',
    'terceros_app',
    'usuarios_app',

]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

X_FRAM_OPTIONS = "SAMEORIGIN"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Justo_proy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Justo_proy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'JustoWare',
#         'USER': 'root',
#         'PASSWORD': 'MariaDB2023',
#         'HOST': 'localhost',
#         'PORT': '2023',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'otra',
        'USER': 'root',
        'PASSWORD': 'MariaDB2023',
        'HOST': 'localhost',
        'PORT': '2023',

    }
}
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite1',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# AUTH_USER_MODEL = 'tu_app.UsuarioPersonalizado'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Define la ruta de la carpeta 'assets' dentro del directorio principal
ASSETS_DIR = os.path.join(BASE_DIR, 'assets')
STATICFILES_DIRS = [
    ASSETS_DIR,
]

# Cerrar la sesión automaticamente después de determinado tiempo
# SESSION_COOKIE_AGE = 60

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.example.com'  # Configura esto con tu servidor SMTP
# EMAIL_PORT = 587  # Puerto del servidor SMTP
# EMAIL_USE_TLS = True  # Usar TLS para cifrar la conexión
# # Correo electrónico desde el que se enviarán los correos
# EMAIL_HOST_USER = 'tu_correo@example.com'
# EMAIL_HOST_PASSWORD = 'tu_contraseña'  # Contraseña del correo electrónico
