# Generated by Django 4.2.4 on 2024-03-11 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_app', '0006_alter_clientes_fin_lic_alter_clientes_ini_lic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DESTINO_CRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('descripcion', models.CharField(max_length=50, null=True, verbose_name='Descripción')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_app.clientes', verbose_name='Cliente')),
            ],
            options={
                'db_table': 'destino_cre',
                'unique_together': {('cliente', 'codigo')},
            },
        ),
    ]
