# Generated by Django 4.2.4 on 2024-06-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localidades_app', '0002_alter_localidades_cliente'),
        ('terceros_app', '0002_alter_terceros_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='cod_ciu_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciu_exp', to='localidades_app.localidades', verbose_name='Ciudad Expedición Documento'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='cod_ciu_res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciu_res', to='localidades_app.localidades', verbose_name='Ciudad Residencia'),
        ),
    ]
