# Generated by Django 4.2.4 on 2024-02-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0002_alter_terceros_celular1_alter_terceros_celular2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='dig_ver',
            field=models.CharField(max_length=1, verbose_name='DV'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='nit_rap',
            field=models.CharField(max_length=12, verbose_name='Nit Rápido'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='observacion',
            field=models.CharField(max_length=255, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='raz_soc',
            field=models.CharField(max_length=120, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='seg_ape',
            field=models.CharField(max_length=28, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='seg_nom',
            field=models.CharField(max_length=28, verbose_name='Segundo Nombre'),
        ),
    ]
