# Generated by Django 4.2.4 on 2024-02-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0004_estados_fin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ESTADOS_FIN',
        ),
    ]
