# Generated by Django 4.2.4 on 2024-02-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_app', '0006_alter_terceros_dig_ver_alter_terceros_nit_rap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='id_ds',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='observacion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Observación'),
        ),
    ]
