# Generated by Django 4.2.4 on 2024-03-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_app', '0006_alter_clientes_fin_lic_alter_clientes_ini_lic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONCEPTOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_con', models.CharField(max_length=8)),
                ('con_justo', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('descripcion', models.CharField(max_length=44)),
                ('tip_dev_ap', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('tip_con', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('tip_sis', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('cta_con', models.CharField(max_length=10)),
                ('cta_con_pas', models.CharField(max_length=10)),
                ('debito', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('credito', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('por_tercero', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('por_ret_fue', models.FloatField(blank=True, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes_app.clientes')),
            ],
            options={
                'db_table': 'conceptos',
                'unique_together': {('cliente', 'cod_con')},
            },
        ),
    ]
