# Generated by Django 4.2.4 on 2024-05-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptos',
            name='por_ret_fue',
            field=models.FloatField(blank=True, null=True, verbose_name='% Retefuente?'),
        ),
    ]
