# Generated by Django 4.2.4 on 2024-04-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptos_app', '0002_alter_conceptos_cliente_alter_conceptos_cod_con_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptos',
            name='cta_con',
            field=models.CharField(blank=True, max_length=10, verbose_name='Cuenta Contable'),
        ),
        migrations.AlterField(
            model_name='conceptos',
            name='cta_con_pas',
            field=models.CharField(blank=True, max_length=10, verbose_name='Cuenta Contable Pasivo'),
        ),
        migrations.AlterField(
            model_name='conceptos',
            name='por_ret_fue',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Usa Retefuente?'),
        ),
    ]
