# Generated by Django 4.2.4 on 2024-06-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0001_initial'),
        ('conceptos_app', '0002_alter_conceptos_por_ret_fue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptos',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes_app.clientes', verbose_name='Cliente'),
        ),
    ]
