# Generated by Django 4.2.4 on 2024-02-06 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='COMPROBANTES',
        ),
    ]
