# Generated by Django 4.2.4 on 2024-02-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0003_creditos_cat_his'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='ali_cuota',
            field=models.FloatField(null=True),
        ),
    ]
