# Generated by Django 4.2.4 on 2024-02-12 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0004_alter_creditos_cat_his_ali_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditos_cat_his',
            name='credito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='justo_app.creditos'),
        ),
        migrations.CreateModel(
            name='CREDITOS_CAT_DET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cre', models.CharField(max_length=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fec_ref', models.DateField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=1, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('val_ali', models.FloatField(blank=True, null=True)),
                ('clave', models.SmallIntegerField(null=True)),
                ('credito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='justo_app.creditos')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justo_app.oficinas')),
            ],
            options={
                'db_table': 'creditos_cat_det',
                'unique_together': {('oficina', 'fecha', 'cod_cre')},
            },
        ),
    ]
