# Generated by Django 4.2.4 on 2024-02-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0006_alter_creditos_cat_det_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditos',
            name='cod_lin_cre',
            field=models.IntegerField(null=True),
        ),
    ]
