# Generated by Django 4.2.4 on 2024-02-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0007_creditos_cod_lin_cre'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='creditos_cat_his',
            index=models.Index(fields=['oficina', 'fecha', 'nit'], name='creditos_ca_oficina_f1ef77_idx'),
        ),
    ]
