# Generated by Django 4.2.4 on 2024-02-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0009_cate_inte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cate_inte',
            name='cau_ZC',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='cau_ZD',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='cau_ZE',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='cau_ZET',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='cau_ZF',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='cue_por_pag',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='cue_pr_cob_A',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='cue_pr_cob_B',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='cue_pr_cob_C',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='cue_pr_cob_D',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='cue_pr_cob_E',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='cue_pr_cob_F',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='final',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='gas_gen_ind_fin',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='gas_gen_ind_ini',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='gas_pro_ind_fin',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='gas_pro_ind_ini',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='ingreso',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='inicio',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='int_cau_fin',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='int_cau_ini',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='int_cau_mes',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='int_con',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='int_dia_fin',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='int_dia_ini',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='int_pag',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='int_pag_act',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='int_pag_ade',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='int_pag_ant',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='ip_ant_A',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='ip_ant_B',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='ip_ant_C',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='ip_ant_D',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='ip_ant_E',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='ip_ant_Z',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='ip_ant_ZC',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='ip_ant_ZD',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='ip_ant_ZE',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='ip_ant_ZF',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='plazo',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='pro_gen_fin',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='pro_gen_ini',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='pro_ind_fin',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='pro_ind_ini',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='sal_cap_fin',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='sal_cap_ini',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
