# Generated by Django 4.2.4 on 2024-02-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0010_alter_cate_inte_cau_zc_alter_cate_inte_cau_zd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cate_inte',
            old_name='gas_gen_ind_fin',
            new_name='gas_gen_fin',
        ),
        migrations.RenameField(
            model_name='cate_inte',
            old_name='gas_gen_ind_ini',
            new_name='gas_gen_ini',
        ),
    ]
