# Generated by Django 4.2.4 on 2024-02-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0011_rename_gas_gen_ind_fin_cate_inte_gas_gen_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cate_inte',
            name='arr_fin',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='arr_ini',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='cat_fin',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='cat_ini',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cate_inte',
            name='cre_con_cas',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default=' ', max_length=1),
        ),
    ]
