# Generated by Django 4.2.4 on 2024-02-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0013_alter_cate_inte_cau_zc_alter_cate_inte_cau_zd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditos_cat_det',
            name='cod_cre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='creditos_cat_det',
            name='fecha',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='ali_cuota',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='aporte',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='arrastre',
            field=models.CharField(default=0.0, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='cap_ini',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='castigo',
            field=models.CharField(default=0.0, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='cat_eva',
            field=models.CharField(default=0.0, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='cat_int_mes',
            field=models.CharField(default=0.0, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='cat_mod',
            field=models.CharField(default=0.0, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='cat_ree',
            field=models.CharField(default=0.0, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='cat_sel',
            field=models.CharField(default=0.0, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='categoria',
            field=models.CharField(default=0.0, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='conta_per',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='dias_mor',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='gas_pro_gen',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='gas_pro_ind',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='int_cau_res_per',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='int_cor_per',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='pdi',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='per_esp',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='plazo',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='pro_inc',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='pro_ind',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='puntaje',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='sal_cap',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='sal_cap_dia',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='sal_cat_int',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='sal_int_dia',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='saldo_1',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='saldo_2',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='vea',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='vr_gar_hip',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='zeta',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
