# Generated by Django 4.2.4 on 2024-02-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0014_alter_creditos_cat_det_cod_cre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='arrastre',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='categoria',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
    ]
