# Generated by Django 4.2.4 on 2024-02-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0016_alter_creditos_cat_his_cat_int_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='castigo',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
    ]
