# Generated by Django 4.2.4 on 2024-02-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0017_alter_creditos_cat_his_castigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='cat_eva',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='cat_mod',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='cat_ree',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='creditos_cat_his',
            name='cat_sel',
            field=models.CharField(default=' ', max_length=1, null=True),
        ),
    ]
