# Generated by Django 4.2.4 on 2024-02-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0018_alter_creditos_cat_his_cat_eva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditos_cat_his',
            name='int_pag_per',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
