# Generated by Django 4.2.4 on 2024-02-15 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0020_creditos_cat_his_int_conokas_per'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditos_cat_his',
            old_name='int_conokas_per',
            new_name='int_conkas_per',
        ),
    ]
