# Generated by Django 4.2.4 on 2024-02-17 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0021_rename_int_conokas_per_creditos_cat_his_int_conkas_per'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imp_con_cre_int',
            old_name='kporcentaje',
            new_name='porcen_det',
        ),
    ]
