# Generated by Django 4.2.4 on 2024-02-17 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0022_rename_kporcentaje_imp_con_cre_int_porcen_det'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imp_con_cre',
            old_name='icta_des_int_pp',
            new_name='k_pte_ic',
        ),
        migrations.RenameField(
            model_name='imp_con_cre',
            old_name='kcta_gas_pro_gen',
            new_name='kdet_gen',
        ),
        migrations.RenameField(
            model_name='imp_con_cre',
            old_name='kcta_gas_pro_ind',
            new_name='kdet_gen_adi',
        ),
        migrations.RenameField(
            model_name='imp_con_cre',
            old_name='kcta_pro_gen',
            new_name='kdet_gen_gas',
        ),
        migrations.RenameField(
            model_name='imp_con_cre',
            old_name='kcta_pro_gen_adi',
            new_name='kdet_gen_rec',
        ),
        migrations.RenameField(
            model_name='imp_con_cre',
            old_name='kcta_pte_cap',
            new_name='kdet_ind_gas',
        ),
        migrations.RenameField(
            model_name='imp_con_cre',
            old_name='kcta_pte_int',
            new_name='kdet_ind_rec',
        ),
        migrations.RenameField(
            model_name='imp_con_cre',
            old_name='kcta_rec_pro_gen',
            new_name='kdpp_ic',
        ),
        migrations.RenameField(
            model_name='imp_con_cre',
            old_name='kcta_rec_pro_ind',
            new_name='kpte_cap',
        ),
    ]
