# Generated by Django 4.2.4 on 2024-02-17 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0023_rename_icta_des_int_pp_imp_con_cre_k_pte_ic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imp_con_cre',
            old_name='orden_i',
            new_name='kic_orden_i',
        ),
    ]
