# Generated by Django 4.2.4 on 2024-02-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0025_rename_k_pte_ic_imp_con_cre_kpte_ic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imp_con_cre_int',
            old_name='cta_int',
            new_name='kcapital',
        ),
        migrations.RenameField(
            model_name='imp_con_cre_int',
            old_name='cta_ord_int',
            new_name='kcxc_ic',
        ),
        migrations.RenameField(
            model_name='imp_con_cre_int',
            old_name='kcta_con',
            new_name='kdet_ind',
        ),
        migrations.RenameField(
            model_name='imp_con_cre_int',
            old_name='kcta_pro_ind',
            new_name='kord_ic',
        ),
    ]
