# Generated by Django 4.2.4 on 2024-02-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0026_rename_cta_int_imp_con_cre_int_kcapital_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditos_cat_det',
            old_name='val_ali',
            new_name='val_det',
        ),
        migrations.AddField(
            model_name='cate_inte',
            name='fec_des',
            field=models.DateField(blank=True, null=True),
        ),
    ]
