# Generated by Django 4.2.4 on 2024-02-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0029_remove_cate_inte_cod_ic_fin_remove_cate_inte_plazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cate_inte',
            name='det_ind_gas_acu',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='creditos_cat_his',
            name='det_ind_gas_acu',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
