# Generated by Django 4.2.4 on 2024-02-22 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0030_cate_inte_det_ind_gas_acu_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='creditos_cat_det',
            unique_together={('oficina', 'fecha', 'cod_cre', 'fec_ref', 'categoria')},
        ),
    ]
