# Generated by Django 4.2.4 on 2024-02-24 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0031_alter_creditos_cat_det_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='clase_coop',
            field=models.CharField(choices=[('AS', 'Asociaciones Mutuales'), ('TA', 'Trabajo Asociado'), ('EAYC', 'Especializada de Ahorro Y Credito'), ('ESSA', 'Especializada sin Seccion de Ahorro'), ('FE', 'Fondo de Empleados'), ('ISSA', 'Integral Sin Seccion de Ahorro'), ('MASSA', 'Multi Activa Sin Seccion de Ahorros')], default='EAYC', max_length=8),
        ),
        migrations.CreateModel(
            name='PE_CALIFICION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_coop', models.CharField(choices=[('AS', 'Asociaciones Mutuales'), ('TA', 'Trabajo Asociado'), ('EAYC', 'Especializada de Ahorro Y Credito'), ('ESSA', 'Especializada sin Seccion de Ahorro'), ('FE', 'Fondo de Empleados'), ('ISSA', 'Integral Sin Seccion de Ahorro'), ('MASSA', 'Multi Activa Sin Seccion de Ahorros')], max_length=8)),
                ('calificacion', models.CharField(max_length=1)),
                ('pi_porcent', models.FloatField(blank=True, default=0.0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justo_app.clientes')),
            ],
            options={
                'db_table': 'pe_calificacion',
                'unique_together': {('cliente', 'clase_coop', 'calificacion')},
            },
        ),
    ]
