# Generated by Django 4.2.4 on 2024-02-25 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0035_pe_cali_punt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pe_calificion',
            old_name='pi_porcent',
            new_name='pi_puntaje',
        ),
    ]
