# Generated by Django 4.2.4 on 2024-02-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0036_rename_pi_porcent_pe_calificion_pi_puntaje'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PE_CALI_PUNT',
            new_name='PE_CALI_PORC',
        ),
        migrations.AlterModelTable(
            name='pe_cali_porc',
            table='pe_cali_porc',
        ),
    ]
