# Generated by Django 4.2.4 on 2024-02-25 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0037_rename_pe_cali_punt_pe_cali_porc_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PE_CALI_PORC',
            new_name='PE_CALI_RANGO',
        ),
        migrations.AlterModelTable(
            name='pe_cali_rango',
            table='pe_cali_rango',
        ),
    ]
