# Generated by Django 4.2.4 on 2024-02-25 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0038_rename_pe_cali_porc_pe_cali_rango_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PE_CALIFICION',
            new_name='PE_CALIF_RANGO',
        ),
        migrations.RenameModel(
            old_name='PE_CALI_RANGO',
            new_name='PE_PI_CALIF',
        ),
        migrations.AlterModelTable(
            name='pe_calif_rango',
            table='pe_calif_rango',
        ),
        migrations.AlterModelTable(
            name='pe_pi_calif',
            table='pe__pi_calif',
        ),
    ]
