# Generated by Django 4.2.4 on 2024-02-25 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0039_rename_pe_calificion_pe_calif_rango_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PE_PDI_RANGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garantia', models.CharField(choices=[('1', 'No Idonea'), ('2', 'Hipotecaria'), ('15', 'Sin Garantias')], default='15', max_length=2)),
                ('dias_inc_0', models.SmallIntegerField(default=0)),
                ('pdi_0', models.FloatField(blank=True, default=0.0)),
                ('dias_inc_1', models.SmallIntegerField(default=0)),
                ('pdi_1', models.FloatField(blank=True, default=0.0)),
                ('dias_inc_2', models.SmallIntegerField(default=0)),
                ('pdi_2', models.FloatField(blank=True, default=0.0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justo_app.clientes')),
            ],
            options={
                'db_table': 'pe__pdi_rango',
                'unique_together': {('cliente', 'garantia')},
            },
        ),
    ]
