# Generated by Django 4.2.4 on 2024-02-25 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0040_pe_pdi_rango'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pe_pdi_rango',
            name='dias_inc_0',
        ),
    ]
