# Generated by Django 4.2.4 on 2024-02-25 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0041_remove_pe_pdi_rango_dias_inc_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='PE_MODE_REFE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('CCCL', 'Consumo Con Libranza'), ('CCSL', 'Consumo sin Libranza'), ('CCPJ', 'Comercial Juridica'), ('CCPN', 'Comercial Natural'), ('CMIC', 'MicroCredito')], max_length=6)),
                ('constante', models.FloatField(blank=True, default=0.0)),
                ('coe_ea', models.FloatField(blank=True, default=0.0)),
                ('coe_ap', models.FloatField(blank=True, default=0.0)),
                ('coe_tc', models.FloatField(blank=True, default=0.0)),
                ('coe_fe', models.FloatField(blank=True, default=0.0)),
                ('coe_esim', models.FloatField(blank=True, default=0.0)),
                ('coe_famor', models.FloatField(blank=True, default=0.0)),
                ('coe_valcuota', models.FloatField(blank=True, default=0.0)),
                ('coe_valpres', models.FloatField(blank=True, default=0.0)),
                ('coe_ocoop', models.FloatField(blank=True, default=0.0)),
                ('coe_fonaho', models.FloatField(blank=True, default=0.0)),
                ('coe_coopcdat', models.FloatField(blank=True, default=0.0)),
                ('coe_fondplazo', models.FloatField(blank=True, default=0.0)),
                ('coe_antipre1', models.FloatField(blank=True, default=0.0)),
                ('coe_mora15', models.FloatField(blank=True, default=0.0)),
                ('coe_mora1230', models.FloatField(blank=True, default=0.0)),
                ('coe_mora1260', models.FloatField(blank=True, default=0.0)),
                ('coe_mora2430', models.FloatField(blank=True, default=0.0)),
                ('coe_mora2460', models.FloatField(blank=True, default=0.0)),
                ('coe_simmora', models.FloatField(blank=True, default=0.0)),
                ('coe_mortrim', models.FloatField(blank=True, default=0.0)),
                ('coe_reest', models.FloatField(blank=True, default=0.0)),
                ('coe_cuenaho', models.FloatField(blank=True, default=0.0)),
                ('coe_cdat', models.FloatField(blank=True, default=0.0)),
                ('coe_per', models.FloatField(blank=True, default=0.0)),
                ('coe_entidad1', models.FloatField(blank=True, default=0.0)),
                ('coe_antipre2', models.FloatField(blank=True, default=0.0)),
                ('coe_vin2', models.FloatField(blank=True, default=0.0)),
                ('coe_mora3615', models.FloatField(blank=True, default=0.0)),
                ('coe_entidad2', models.FloatField(blank=True, default=0.0)),
                ('coe_plazol', models.FloatField(blank=True, default=0.0)),
                ('coe_salpres', models.FloatField(blank=True, default=0.0)),
                ('coe_m1mora30', models.FloatField(blank=True, default=0.0)),
                ('coe_m2mora30', models.FloatField(blank=True, default=0.0)),
                ('coe_m1mora30m3', models.FloatField(blank=True, default=0.0)),
                ('coe_amor', models.FloatField(blank=True, default=0.0)),
                ('coe_nodo4', models.FloatField(blank=True, default=0.0)),
                ('coe_nodo5', models.FloatField(blank=True, default=0.0)),
                ('coe_nodo7', models.FloatField(blank=True, default=0.0)),
                ('coe_nodo8', models.FloatField(blank=True, default=0.0)),
                ('coe_nodo9', models.FloatField(blank=True, default=0.0)),
                ('coe_nodo1', models.FloatField(blank=True, default=0.0)),
                ('coe_mora3660', models.FloatField(blank=True, default=0.0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justo_app.clientes')),
            ],
            options={
                'db_table': 'pe__mode_refe',
                'unique_together': {('cliente', 'modalidad')},
            },
        ),
    ]
