# Generated by Django 4.2.4 on 2024-02-25 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0042_pe_mode_refe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CREDITOS_CAT_DET',
            new_name='CARTERA_CXC',
        ),
        migrations.AlterModelTable(
            name='cartera_cxc',
            table='cartera_cxc',
        ),
    ]
