# Generated by Django 4.2.4 on 2024-02-25 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0043_rename_creditos_cat_det_cartera_cxc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PE_CARTE_HIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True)),
                ('cod_cre', models.CharField(max_length=10, null=True)),
                ('modalidad', models.CharField(choices=[('CCCL', 'Consumo Con Libranza'), ('CCSL', 'Consumo sin Libranza'), ('CCPJ', 'Comercial Juridica'), ('CCPN', 'Comercial Natural'), ('CMIC', 'MicroCredito')], max_length=6)),
                ('calificacion', models.CharField(max_length=1, null=True)),
                ('pe', models.FloatField(blank=True, default=0.0)),
                ('pi', models.FloatField(blank=True, default=0.0)),
                ('vea', models.FloatField(blank=True, default=0.0)),
                ('pdi', models.FloatField(blank=True, default=0.0)),
                ('puntaje', models.FloatField(blank=True, default=0.0)),
                ('z', models.FloatField(blank=True, default=0.0)),
                ('val_ea', models.SmallIntegerField(default=0)),
                ('val_ap', models.SmallIntegerField(default=0)),
                ('val_tc', models.SmallIntegerField(default=0)),
                ('val_fe', models.SmallIntegerField(default=0)),
                ('val_esim', models.SmallIntegerField(default=0)),
                ('val_famor', models.SmallIntegerField(default=0)),
                ('val_valcuota', models.SmallIntegerField(default=0)),
                ('val_valpres', models.SmallIntegerField(default=0)),
                ('val_ocoop', models.SmallIntegerField(default=0)),
                ('val_fonaho', models.SmallIntegerField(default=0)),
                ('val_coopcdat', models.SmallIntegerField(default=0)),
                ('val_fondplazo', models.SmallIntegerField(default=0)),
                ('val_antipre1', models.SmallIntegerField(default=0)),
                ('val_mora15', models.SmallIntegerField(default=0)),
                ('val_mora1230', models.SmallIntegerField(default=0)),
                ('val_mora1260', models.SmallIntegerField(default=0)),
                ('val_mora2430', models.SmallIntegerField(default=0)),
                ('val_mora2460', models.SmallIntegerField(default=0)),
                ('val_simmora', models.SmallIntegerField(default=0)),
                ('val_mortrim', models.SmallIntegerField(default=0)),
                ('val_reest', models.SmallIntegerField(default=0)),
                ('val_cuenaho', models.SmallIntegerField(default=0)),
                ('val_cdat', models.SmallIntegerField(default=0)),
                ('val_per', models.SmallIntegerField(default=0)),
                ('val_entidad1', models.SmallIntegerField(default=0)),
                ('val_antipre2', models.SmallIntegerField(default=0)),
                ('val_vin2', models.SmallIntegerField(default=0)),
                ('val_mora3615', models.SmallIntegerField(default=0)),
                ('val_entidad2', models.SmallIntegerField(default=0)),
                ('val_plazol', models.SmallIntegerField(default=0)),
                ('val_salpres', models.SmallIntegerField(default=0)),
                ('val_m1mora30', models.SmallIntegerField(default=0)),
                ('val_m2mora30', models.SmallIntegerField(default=0)),
                ('val_m1mora30m3', models.SmallIntegerField(default=0)),
                ('val_amor', models.SmallIntegerField(default=0)),
                ('val_nodo4', models.SmallIntegerField(default=0)),
                ('val_nodo5', models.SmallIntegerField(default=0)),
                ('val_nodo7', models.SmallIntegerField(default=0)),
                ('val_nodo8', models.SmallIntegerField(default=0)),
                ('val_nodo9', models.SmallIntegerField(default=0)),
                ('val_nodo1', models.SmallIntegerField(default=0)),
                ('val_mora3660', models.SmallIntegerField(default=0)),
                ('oficina', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='justo_app.oficinas')),
            ],
            options={
                'db_table': 'pe_carte_his',
                'unique_together': {('oficina', 'fecha', 'cod_cre')},
            },
        ),
    ]
