# Generated by Django 4.2.4 on 2024-02-27 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0044_pe_carte_his'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pe_mode_refe',
            old_name='coe_simmora',
            new_name='coe_sinmora',
        ),
    ]
