# Generated by Django 4.2.4 on 2024-02-27 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0045_rename_coe_simmora_pe_mode_refe_coe_sinmora'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CREDITOS_CAT_HIS',
            new_name='CARTE_CAT_HIS',
        ),
        migrations.RenameIndex(
            model_name='carte_cat_his',
            new_name='carte_cat_h_oficina_af2d73_idx',
            old_name='creditos_ca_oficina_f1ef77_idx',
        ),
        migrations.AlterModelTable(
            name='carte_cat_his',
            table='carte_cat_his',
        ),
    ]
