# Generated by Django 4.2.4 on 2024-03-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0049_alter_gar_no_idonea_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pe_pdi_rango',
            table='pe_pdi_rango',
        ),
    ]
