# Generated by Django 4.2.4 on 2024-03-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0050_alter_pe_pdi_rango_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pe_mode_refe',
            table='pe_mode_refe',
        ),
    ]
