# Generated by Django 4.2.4 on 2024-03-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0051_alter_pe_mode_refe_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pe_pi_calif',
            table='pe_pi_calif',
        ),
    ]
