# Generated by Django 4.2.4 on 2024-03-09 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0052_alter_pe_pi_calif_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='INT_DIA_AHO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cta', models.CharField(max_length=10, null=True)),
                ('dia_mes', models.IntegerField()),
                ('fecha', models.DateField(blank=True)),
                ('int_dia', models.BigIntegerField()),
                ('ret_fue', models.BigIntegerField()),
                ('aplicado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('cta_aho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justo_app.ctas_ahorro')),
                ('oficina', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='justo_app.oficinas')),
            ],
            options={
                'db_table': 'int_dia_aho',
                'unique_together': {('oficina', 'cta_aho', 'dia_mes')},
            },
        ),
    ]
