# Generated by Django 4.2.4 on 2024-03-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0055_alter_int_dia_aho_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='int_dia_aho',
            name='int_dia',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='int_dia_aho',
            name='ret_fue',
            field=models.BigIntegerField(null=True),
        ),
    ]
