# Generated by Django 4.2.4 on 2024-03-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0056_alter_int_dia_aho_int_dia_alter_int_dia_aho_ret_fue'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cta_cdat_liq',
            index=models.Index(fields=['fecha'], name='cta_cdat_li_fecha_ab1688_idx'),
        ),
    ]
