# Generated by Django 4.2.4 on 2024-03-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justo_app', '0057_cta_cdat_liq_cta_cdat_li_fecha_ab1688_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cta_cdat_liq',
            name='cta_cdat_li_fecha_ab1688_idx',
        ),
        migrations.AddIndex(
            model_name='cta_cdat_amp',
            index=models.Index(fields=['fecha'], name='cta_cdat_am_fecha_574987_idx'),
        ),
    ]
