# Generated by Django 4.2.4 on 2024-05-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XDOC_ZEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_con', models.IntegerField()),
                ('clase_zep', models.CharField(max_length=1)),
                ('doc_ds', models.IntegerField(null=True)),
                ('nombre', models.CharField(blank=True, max_length=16)),
                ('descripcion', models.CharField(blank=True, max_length=36)),
            ],
            options={
                'db_table': 'xdoc_zep',
                'unique_together': {('per_con', 'clase_zep')},
            },
        ),
    ]
