# Generated by Django 4.2.4 on 2024-06-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asociados_app', '0002_alter_aso_benef_asociado_and_more'),
        ('originacion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originacion',
            name='asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asociados_app.asociados', verbose_name='Asociado'),
        ),
    ]
