# Generated by Django 4.2.4 on 2024-03-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficinas_app', '0002_oficinas_ciudad_oficinas_direccion_alter_oficinas_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='USUARIOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=16)),
                ('nit', models.CharField(max_length=12, null=True)),
                ('nombre', models.CharField(max_length=44, null=True)),
                ('fec_ing', models.DateField(blank=True, null=True)),
                ('es_cajero', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('cod_caj', models.CharField(max_length=2, null=True)),
                ('fec_sal', models.DateField(blank=True, null=True)),
                ('cta_con_acr', models.CharField(max_length=10, null=True)),
                ('activo', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('oficina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oficinas_app.oficinas')),
            ],
            options={
                'db_table': 'usuarios',
                'unique_together': {('oficina', 'login')},
            },
        ),
    ]
