# Generated by Django 4.2.4 on 2024-03-30 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficinas_app', '0002_oficinas_ciudad_oficinas_direccion_alter_oficinas_id'),
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='activo',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Está Activo?'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='cod_caj',
            field=models.CharField(max_length=2, null=True, verbose_name='Código Cajero'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='cta_con_acr',
            field=models.CharField(max_length=10, null=True, verbose_name='Cuenta Contable'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='es_cajero',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Es Cajero?'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fec_ing',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fec_sal',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Saldo'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='login',
            field=models.CharField(max_length=16, verbose_name='Nombre Usuario'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nit',
            field=models.CharField(max_length=12, null=True, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=44, null=True, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='oficina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oficinas_app.oficinas', verbose_name='Oficina'),
        ),
    ]
