# Generated by Django 4.2.4 on 2024-06-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0001_initial'),
        ('terceros_app', '0002_alter_terceros_cliente'),
        ('estados_financieros_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estados_fin',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes_app.clientes', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='estados_fin',
            name='tercero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='terceros_app.terceros', verbose_name='Tercero'),
        ),
    ]
