# Generated by Django 4.2.4 on 2024-03-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centrocostos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DETALLE_PROD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[('AP', 'Aportes'), ('AH', 'Ahorros'), ('CR', 'Créditos'), ('CC', 'Cuenta por Cobrar'), ('CP', 'Cuenta por Pagar'), ('CO', 'Contable'), ('BA', 'Bancos')], max_length=2, verbose_name='Producto')),
                ('subcuenta', models.CharField(max_length=12, null=True, verbose_name='Subcuenta')),
                ('concepto', models.CharField(max_length=8, null=True, verbose_name='Concepto')),
                ('valor', models.FloatField(null=True, verbose_name='Valor')),
                ('usuario', models.CharField(max_length=12, null=True, verbose_name='Usuario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('centro_costo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='centrocostos_app.centrocostos', verbose_name='Centro de Costo')),
            ],
            options={
                'db_table': 'detalle_prod',
            },
        ),
    ]
