# Generated by Django 4.2.4 on 2024-06-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centrocostos_app', '0002_alter_centrocostos_oficina'),
        ('oficinas_app', '0001_initial'),
        ('hecho_economico_app', '0002_alter_hecho_econo_anulado_alter_hecho_econo_canal_and_more'),
        ('detalle_producto_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_prod',
            name='centro_costo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='centrocostos_app.centrocostos', verbose_name='Centro de Costo'),
        ),
        migrations.AlterField(
            model_name='detalle_prod',
            name='hecho_econo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hecho_economico_app.hecho_econo', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='detalle_prod',
            name='oficina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas', verbose_name='Oficina'),
        ),
    ]
