# Generated by Django 4.2.4 on 2024-03-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hecho_economico_app', '0001_initial'),
        ('detalle_producto_app', '0001_initial'),
        ('oficinas_app', '0002_oficinas_ciudad_oficinas_direccion_alter_oficinas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_prod',
            name='hecho_econo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hecho_economico_app.hecho_econo', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='detalle_prod',
            name='oficina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oficinas_app.oficinas', verbose_name='Oficina'),
        ),
        migrations.AddIndex(
            model_name='detalle_prod',
            index=models.Index(fields=['oficina', 'producto', 'subcuenta'], name='detalle_pro_oficina_9a63d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detalle_prod',
            unique_together={('hecho_econo', 'producto', 'subcuenta', 'concepto')},
        ),
    ]
