# Generated by Django 4.2.4 on 2024-05-06 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lineas_ahorro_app', '0001_initial'),
        ('oficinas_app', '0001_initial'),
        ('asociados_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTAS_AHORRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cta', models.CharField(max_length=10, null=True, verbose_name='Número Cuenta')),
                ('est_cta', models.CharField(choices=[('A', 'Activa'), ('I', 'Inactiva'), ('C', 'Cancelada'), ('E', 'Embargada')], max_length=1, verbose_name='Estado Cuenta')),
                ('fec_apertura', models.DateField(blank=True, null=True, verbose_name='Fecha Apertura')),
                ('fec_cancela', models.DateField(blank=True, null=True, verbose_name='Fecha Cancelación')),
                ('exc_tas_mil', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Exenta 4x1000')),
                ('fec_ini_exc', models.DateField(blank=True, null=True, verbose_name='Fecha Exención')),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociados_app.asociados', verbose_name='Nombre Asociado')),
                ('lin_aho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineas_ahorro_app.lineas_ahorro', verbose_name='Línea de Ahorro')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficinas_app.oficinas', verbose_name='Oficina')),
            ],
            options={
                'db_table': 'ctas_ahorro',
                'unique_together': {('oficina', 'num_cta')},
            },
        ),
    ]
