# Generated by Django 4.2.4 on 2024-06-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineas_ahorro_app', '0001_initial'),
        ('oficinas_app', '0001_initial'),
        ('asociados_app', '0002_alter_aso_benef_asociado_and_more'),
        ('ctas_ahorros_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctas_ahorro',
            name='asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asociados_app.asociados', verbose_name='Nombre Asociado'),
        ),
        migrations.AlterField(
            model_name='ctas_ahorro',
            name='lin_aho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lineas_ahorro_app.lineas_ahorro', verbose_name='Línea de Ahorro'),
        ),
        migrations.AlterField(
            model_name='ctas_ahorro',
            name='oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas', verbose_name='Oficina'),
        ),
    ]
