# Generated by Django 4.2.4 on 2024-02-27 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asociados_app', '0001_initial'),
        ('ctas_ahorros_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctas_ahorro',
            name='asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociados_app.asociados', verbose_name='Nombre Asociado'),
        ),
    ]
