# Generated by Django 4.2.4 on 2024-02-27 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localidades_app', '0001_initial'),
        ('oficinas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficinas',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidades_app.localidades', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='oficinas',
            name='direccion',
            field=models.CharField(max_length=80, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='oficinas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
