# Generated by Django 4.2.4 on 2024-03-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CREDITOS_CAUSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cre', models.CharField(max_length=10, null=True)),
                ('cuota', models.IntegerField(default=0)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('capital', models.FloatField(blank=True, null=True)),
                ('int_cor', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'creditos_causa',
            },
        ),
    ]
