# Generated by Django 4.2.4 on 2024-03-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('causacion_creditos_app', '0001_initial'),
        ('detalle_producto_app', '0001_initial'),
        ('oficinas_app', '0002_oficinas_ciudad_oficinas_direccion_alter_oficinas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditos_causa',
            name='comprobante',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='detalle_producto_app.detalle_prod'),
        ),
        migrations.AddField(
            model_name='creditos_causa',
            name='oficina',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='oficinas_app.oficinas'),
        ),
        migrations.AlterUniqueTogether(
            name='creditos_causa',
            unique_together={('oficina', 'cod_cre', 'comprobante', 'cuota')},
        ),
    ]
