# Generated by Django 4.2.4 on 2024-06-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_producto_app', '0001_initial'),
        ('oficinas_app', '0001_initial'),
        ('causacion_creditos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditos_causa',
            name='comprobante',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='detalle_producto_app.detalle_prod', verbose_name='Comprobante'),
        ),
        migrations.AlterField(
            model_name='creditos_causa',
            name='oficina',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas', verbose_name='Oficina'),
        ),
    ]
