# Generated by Django 4.2.4 on 2024-03-30 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_producto_app', '0002_initial'),
        ('oficinas_app', '0002_oficinas_ciudad_oficinas_direccion_alter_oficinas_id'),
        ('causacion_creditos_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditos_causa',
            name='capital',
            field=models.FloatField(blank=True, null=True, verbose_name='Capital'),
        ),
        migrations.AlterField(
            model_name='creditos_causa',
            name='cod_cre',
            field=models.CharField(max_length=10, null=True, verbose_name='Código Crédito'),
        ),
        migrations.AlterField(
            model_name='creditos_causa',
            name='comprobante',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='detalle_producto_app.detalle_prod', verbose_name='Comprobante'),
        ),
        migrations.AlterField(
            model_name='creditos_causa',
            name='cuota',
            field=models.IntegerField(default=0, verbose_name='Cuota'),
        ),
        migrations.AlterField(
            model_name='creditos_causa',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='creditos_causa',
            name='int_cor',
            field=models.FloatField(blank=True, null=True, verbose_name='Interés Corriente'),
        ),
        migrations.AlterField(
            model_name='creditos_causa',
            name='oficina',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='oficinas_app.oficinas', verbose_name='Oficina'),
        ),
    ]
