# Generated by Django 4.2.4 on 2024-03-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ctas_ahorros_app', '0003_alter_ctas_ahorro_asociado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTA_CDAT_AMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('num_liq', models.IntegerField(blank=True, null=True, verbose_name='Número Liquidación')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('cta_aho_afe', models.CharField(max_length=10, null=True, verbose_name='Cuenta de Ahorro Afectada')),
                ('clase', models.CharField(max_length=1, verbose_name='Clase')),
                ('documento', models.CharField(max_length=10, null=True, verbose_name='Documento')),
                ('aplicado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Aplicado?')),
                ('cta_aho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctas_ahorros_app.ctas_ahorro', verbose_name='Cuenta de Ahorro')),
            ],
            options={
                'db_table': 'cta_cdat_amp',
            },
        ),
    ]
