# Generated by Django 4.2.4 on 2024-03-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cdat_app', '0001_initial'),
        ('ampliacion_cdat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cta_cdat_amp',
            name='cta_amp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdat_app.cta_cdat', verbose_name='Cuenta Ampliación'),
        ),
    ]
