# Generated by Django 4.2.4 on 2024-03-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ampliacion_cdat_app', '0002_initial'),
        ('hecho_economico_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cta_cdat_amp',
            name='docto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hecho_economico_app.hecho_econo', verbose_name='Número Documento'),
        ),
        migrations.AlterUniqueTogether(
            name='cta_cdat_amp',
            unique_together={('cta_aho', 'cta_amp', 'fecha')},
        ),
    ]
