# Generated by Django 4.2.4 on 2024-03-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas_app', '0002_alter_plan_ctas_dinamica_alter_plan_ctas_id_ds'),
    ]

    operations = [
        migrations.CreateModel(
            name='DETALLE_ECONO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_concepto', models.CharField(max_length=6, null=True, verbose_name='Item Concepto')),
                ('detalle', models.TextField(null=True, verbose_name='Detalle')),
                ('debito', models.FloatField(null=True, verbose_name='Valor Débito')),
                ('credito', models.FloatField(null=True, verbose_name='Valor Crédito')),
                ('valor_1', models.FloatField(null=True, verbose_name='Valor 1')),
                ('valor_2', models.FloatField(null=True, verbose_name='Valor 2')),
                ('id_ds', models.BigIntegerField(null=True, verbose_name='id_ds')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas_app.plan_ctas', verbose_name='Cuenta Contable')),
            ],
            options={
                'db_table': 'detalle_econo',
            },
        ),
    ]
