# Generated by Django 4.2.4 on 2024-06-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_producto_app', '0001_initial'),
        ('cuentas_app', '0002_alter_plan_ctas_cliente'),
        ('terceros_app', '0002_alter_terceros_cliente'),
        ('hecho_economico_app', '0002_alter_hecho_econo_anulado_alter_hecho_econo_canal_and_more'),
        ('detalle_economico_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_econo',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentas_app.plan_ctas', verbose_name='Cuenta Contable'),
        ),
        migrations.AlterField(
            model_name='detalle_econo',
            name='detalle_prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='detalle_producto_app.detalle_prod', verbose_name='Detalle Producto'),
        ),
        migrations.AlterField(
            model_name='detalle_econo',
            name='hecho_econo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hecho_economico_app.hecho_econo', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='detalle_econo',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terceros_app.terceros', verbose_name='Tercero'),
        ),
    ]
