# Generated by Django 4.2.4 on 2024-03-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceros_app', '0007_alter_terceros_id_ds_alter_terceros_observacion'),
        ('hecho_economico_app', '0001_initial'),
        ('detalle_economico_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_econo',
            name='hecho_econo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hecho_economico_app.hecho_econo', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='detalle_econo',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terceros_app.terceros', verbose_name='Tercero'),
        ),
        migrations.AddIndex(
            model_name='detalle_econo',
            index=models.Index(fields=['hecho_econo', 'cuenta', 'tercero', 'detalle_prod'], name='detalle_eco_hecho_e_534ad7_idx'),
        ),
    ]
