# Generated by Django 4.2.4 on 2024-05-06 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lineas_ahorro_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAS_LIN_AHO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateField(blank=True, null=True, verbose_name='Fecha Inicial')),
                ('fecha_final', models.DateField(blank=True, null=True, verbose_name='Fecha Final')),
                ('tiae', models.FloatField(verbose_name='Tasa Interés Anual Efectiva')),
                ('lin_aho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineas_ahorro_app.lineas_ahorro', verbose_name='Línea de Ahorro')),
            ],
            options={
                'db_table': 'tas_lin_aho',
                'unique_together': {('lin_aho', 'fecha_inicial')},
            },
        ),
    ]
