# Generated by Django 4.2.4 on 2024-06-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineas_ahorro_app', '0002_alter_lineas_ahorro_cliente'),
        ('tasas_lin_aho_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tas_lin_aho',
            name='lin_aho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lineas_ahorro_app.lineas_ahorro', verbose_name='Línea de Ahorro'),
        ),
    ]
