# Generated by Django 4.2.4 on 2024-06-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineas_credito_app', '0001_initial'),
        ('oficinas_app', '0001_initial'),
        ('detalle_producto_app', '0001_initial'),
        ('terceros_app', '0002_alter_terceros_cliente'),
        ('contabilizacion_capital_creditos_app', '0002_alter_imp_con_cre_cliente'),
        ('asociados_app', '0002_alter_aso_benef_asociado_and_more'),
        ('creditos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeudores',
            name='credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creditos_app.creditos'),
        ),
        migrations.AlterField(
            model_name='codeudores',
            name='oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas'),
        ),
        migrations.AlterField(
            model_name='codeudores',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terceros_app.terceros'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='cod_lin_cre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lineas_credito_app.lineas_credito', verbose_name='Línea de Crédito'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='com_des',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='detalle_producto_app.detalle_prod', verbose_name='Comprobante Desembolso'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='imputacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilizacion_capital_creditos_app.imp_con_cre', verbose_name='Contabilización'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas', verbose_name='Oficina'),
        ),
        migrations.AlterField(
            model_name='creditos',
            name='socio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='asociados_app.asociados', verbose_name='Asociado'),
        ),
    ]
