# Generated by Django 4.2.4 on 2024-06-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0001_initial'),
        ('localidades_app', '0002_alter_localidades_cliente'),
        ('pagadores_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagadores',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='localidades_app.localidades', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='pagadores',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes_app.clientes', verbose_name='Cliente'),
        ),
    ]
