# Generated by Django 4.2.4 on 2024-06-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localidades_app', '0001_initial'),
        ('terceros_app', '0002_alter_terceros_cliente'),
        ('oficinas_app', '0001_initial'),
        ('pagadores_app', '0001_initial'),
        ('asociados_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aso_benef',
            name='asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asociados_app.asociados', verbose_name='Asociado'),
        ),
        migrations.AlterField(
            model_name='aso_referencias',
            name='asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asociados_app.asociados', verbose_name='Asociado'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='ciu_tra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciu_tra', to='localidades_app.localidades', verbose_name='Ciudad de Trabajo'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='id_pag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pagadores_app.pagadores', verbose_name='Empresa Nominadora'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='oficina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oficinas_app.oficinas', verbose_name='Oficina'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='tercero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='terceros_app.terceros', verbose_name='Tercero'),
        ),
    ]
