# Generated by Django 4.2.4 on 2024-03-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociados_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociados',
            name='cod_ciiu',
            field=models.CharField(max_length=12, null=True, verbose_name='Código CIIU'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='emp_num_emp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero Empleados'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='med_con',
            field=models.CharField(max_length=48, null=True, verbose_name='med_con'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='negocio_ant',
            field=models.IntegerField(blank=True, null=True, verbose_name='Antiguedad Negocio'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pension_ent_otr',
            field=models.CharField(max_length=36, null=True, verbose_name='Entidad Otra Pensión'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pension_otr',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Otra Pensión?'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pension_tie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiene Pension'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pep_adm_rec_est',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Administra Recursos del Estado PEP?'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pep_car_pub',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Tiene Cargo Público PEP?'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pep_cargo',
            field=models.CharField(max_length=36, null=True, verbose_name='Cargo PEP'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='pep_eje_pod',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='PEP Eje Pod?'),
        ),
        migrations.AlterField(
            model_name='asociados',
            name='tie_gre_car',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Tiene Gre Car?'),
        ),
    ]
