# Generated by Django 4.2.4 on 2024-03-20 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asociados_app', '0002_alter_asociados_cod_ciiu_alter_asociados_emp_num_emp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aso_benef',
            name='agno_nac',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='aso_benef',
            name='asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociados_app.asociados', verbose_name='Asociado'),
        ),
        migrations.AlterField(
            model_name='aso_benef',
            name='cla_doc',
            field=models.CharField(choices=[('C', 'Cédula de Ciudadanía'), ('T', 'Tarjeta de Identidad'), ('N', 'Nit'), ('R', 'Registro Civil'), ('E', 'Cédula de Extranjería'), ('P', 'Pasaporte'), ('O', 'Otros')], max_length=1, verbose_name='Clase Documento'),
        ),
        migrations.AlterField(
            model_name='aso_benef',
            name='doc_ide',
            field=models.CharField(max_length=12, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='aso_benef',
            name='nombre',
            field=models.CharField(max_length=64, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='aso_benef',
            name='parentesco',
            field=models.CharField(choices=[('0', 'No Aplica'), ('1', 'Esposo(a)'), ('2', 'Hijo(a)'), ('3', 'Padre o Madre'), ('4', 'Abuelo(a)'), ('5', 'Nieto(a)'), ('6', 'Hermano'), ('7', 'Hermana'), ('8', 'Primo(a)'), ('9', 'Otro Familiar')], max_length=1, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='aso_benef',
            name='porcentaje',
            field=models.FloatField(blank=True, null=True, verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='aso_referencias',
            name='asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociados_app.asociados', verbose_name='Asociado'),
        ),
        migrations.AlterField(
            model_name='aso_referencias',
            name='direccion',
            field=models.CharField(max_length=64, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='aso_referencias',
            name='empresa',
            field=models.CharField(max_length=40, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='aso_referencias',
            name='nombre',
            field=models.CharField(max_length=64, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='aso_referencias',
            name='ocupacion',
            field=models.CharField(max_length=32, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='aso_referencias',
            name='parentesco',
            field=models.CharField(choices=[('0', 'No Aplica'), ('1', 'Esposo(a)'), ('2', 'Hijo(a)'), ('3', 'Padre o Madre'), ('4', 'Abuelo(a)'), ('5', 'Nieto(a)'), ('6', 'Hermano'), ('7', 'Hermana'), ('8', 'Primo(a)'), ('9', 'Otro Familiar')], max_length=1, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='aso_referencias',
            name='tel_cel',
            field=models.CharField(max_length=10, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='aso_referencias',
            name='tel_emp',
            field=models.CharField(max_length=10, verbose_name='Teléfono Empresa'),
        ),
        migrations.AlterField(
            model_name='aso_referencias',
            name='tel_fijo',
            field=models.CharField(max_length=10, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='aso_referencias',
            name='tipo_ref',
            field=models.CharField(choices=[('0', 'No Aplica'), ('1', 'Familiar'), ('2', 'Personal'), ('3', 'Bancaria'), ('4', 'Comercial'), ('5', 'Laboral')], max_length=1, verbose_name='Tipo Referencia'),
        ),
    ]
