# Generated by Django 4.2.4 on 2024-03-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficinas_app', '0002_oficinas_ciudad_oficinas_direccion_alter_oficinas_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOV_CAJA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cod_caj', models.CharField(max_length=2)),
                ('jornada', models.CharField(max_length=1)),
                ('saldo_ini', models.FloatField(blank=True, null=True)),
                ('debitos', models.FloatField(blank=True, null=True)),
                ('creditos', models.FloatField(blank=True, null=True)),
                ('val_che_dev', models.FloatField(blank=True, null=True)),
                ('saldo_fin', models.FloatField(blank=True, null=True)),
                ('diferencia', models.FloatField(blank=True, null=True)),
                ('val_cheques', models.FloatField(blank=True, null=True)),
                ('val_vales', models.FloatField(blank=True, null=True)),
                ('cerrado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('monedas', models.JSONField(blank=True, null=True)),
                ('oficina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oficinas_app.oficinas')),
            ],
            options={
                'db_table': 'mov_caja',
                'unique_together': {('oficina', 'fecha', 'cod_caj', 'jornada')},
            },
        ),
    ]
