# Generated by Django 4.2.4 on 2024-06-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctas_ahorros_app', '0002_alter_ctas_ahorro_asociado_alter_ctas_ahorro_lin_aho_and_more'),
        ('ampliacion_cdat_app', '0002_alter_cta_cdat_amp_cta_aho_and_more'),
        ('hecho_economico_app', '0003_alter_hecho_econo_docto_conta'),
        ('liquidacion_cdat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cta_cdat_liq',
            name='cta_aho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ctas_ahorros_app.ctas_ahorro', verbose_name='Cuenta de Ahorro'),
        ),
        migrations.AlterField(
            model_name='cta_cdat_liq',
            name='cta_amp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ampliacion_cdat_app.cta_cdat_amp', verbose_name='Cuenta Ampliación'),
        ),
        migrations.AlterField(
            model_name='cta_cdat_liq',
            name='docto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hecho_economico_app.hecho_econo', verbose_name='Número Documento'),
        ),
    ]
