# Generated by Django 4.2.4 on 2024-04-30 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidacion_cdat_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cta_cdat_liq',
            old_name='Val_int',
            new_name='val_int',
        ),
        migrations.RenameField(
            model_name='cta_cdat_liq',
            old_name='Val_ret',
            new_name='val_ret',
        ),
        migrations.RenameField(
            model_name='cta_cdat_liq',
            old_name='Val_ret_nue',
            new_name='val_ret_nue',
        ),
    ]
