# Generated by Django 4.2.4 on 2024-02-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_ctas',
            name='dinamica',
            field=models.TextField(blank=True, verbose_name='Dinámica'),
        ),
        migrations.AlterField(
            model_name='plan_ctas',
            name='id_ds',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
