# Generated by Django 4.2.4 on 2024-03-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0006_alter_clientes_fin_lic_alter_clientes_ini_lic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='clase_coop',
            field=models.CharField(choices=[('AS', 'Asociaciones Mutuales'), ('TA', 'Trabajo Asociado'), ('EAYC', 'Especializada de Ahorro Y Crédito'), ('ESSA', 'Especializada sin Sección de Ahorros'), ('FE', 'Fondo de Empleados'), ('ISSA', 'Integral Sin Sección de Ahorros'), ('MASSA', 'Multi Activa Sin Sección de Ahorros')], default='EAYC', max_length=8, verbose_name='Clase Cooperativa'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
