# Generated by Django 4.2.4 on 2024-03-11 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_app', '0006_alter_clientes_fin_lic_alter_clientes_ini_lic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LINEAS_CREDITO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_lin_cre', models.IntegerField(verbose_name='Código')),
                ('descripcion', models.CharField(max_length=44, null=True, verbose_name='Descripción')),
                ('tas_int_anu', models.FloatField(null=True, verbose_name='Tasa Interés Anual')),
                ('tas_int_mor', models.FloatField(null=True, verbose_name='Tasa Interés Mora')),
                ('por_pol', models.FloatField(null=True, verbose_name='Porcentaje Póliza')),
                ('por_des_pp', models.FloatField(null=True, verbose_name='Descuento Pronto Pago')),
                ('dia_con_int_mor', models.IntegerField(null=True, verbose_name='Días Condonación Interés Mora')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_app.clientes', verbose_name='Cliente')),
            ],
            options={
                'db_table': 'lineas_credito',
                'unique_together': {('cliente', 'cod_lin_cre')},
            },
        ),
    ]
